/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EditorSiteIdRouteImport } from './routes/editor.$siteId'
import { Route as PreviewSiteSlugRouteImport } from './routes/preview.$siteSlug'
import { Route as SSiteSlugRouteImport } from './routes/s.$siteSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorSiteIdRoute = EditorSiteIdRouteImport.update({
  id: '/editor/$siteId',
  path: '/editor/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewSiteSlugRoute = PreviewSiteSlugRouteImport.update({
  id: '/preview/$siteSlug',
  path: '/preview/$siteSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SSiteSlugRoute = SSiteSlugRouteImport.update({
  id: '/s/$siteSlug',
  path: '/s/$siteSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/editor/$siteId': typeof EditorSiteIdRoute
  '/preview/$siteSlug': typeof PreviewSiteSlugRoute
  '/s/$siteSlug': typeof SSiteSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/editor/$siteId': typeof EditorSiteIdRoute
  '/preview/$siteSlug': typeof PreviewSiteSlugRoute
  '/s/$siteSlug': typeof SSiteSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/editor/$siteId': typeof EditorSiteIdRoute
  '/preview/$siteSlug': typeof PreviewSiteSlugRoute
  '/s/$siteSlug': typeof SSiteSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/editor/$siteId'
    | '/preview/$siteSlug'
    | '/s/$siteSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/editor/$siteId'
    | '/preview/$siteSlug'
    | '/s/$siteSlug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/editor/$siteId'
    | '/preview/$siteSlug'
    | '/s/$siteSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  EditorSiteIdRoute: typeof EditorSiteIdRoute
  PreviewSiteSlugRoute: typeof PreviewSiteSlugRoute
  SSiteSlugRoute: typeof SSiteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$siteId': {
      id: '/editor/$siteId'
      path: '/editor/$siteId'
      fullPath: '/editor/$siteId'
      preLoaderRoute: typeof EditorSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$siteSlug': {
      id: '/preview/$siteSlug'
      path: '/preview/$siteSlug'
      fullPath: '/preview/$siteSlug'
      preLoaderRoute: typeof PreviewSiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$siteSlug': {
      id: '/s/$siteSlug'
      path: '/s/$siteSlug'
      fullPath: '/s/$siteSlug'
      preLoaderRoute: typeof SSiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  EditorSiteIdRoute: EditorSiteIdRoute,
  PreviewSiteSlugRoute: PreviewSiteSlugRoute,
  SSiteSlugRoute: SSiteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
